[package]
name = "based64"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
paste = "1.0.15"
wasm-bindgen = "0.2.93"

[dev-dependencies]
wasm-bindgen-test = "0.3.43"
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib", "rlib"]
